#!/usr/bin/env bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

set -e

echo "Running official tests..."
$DIR/test-cases $DIR/../ref/sxpy $1 $DIR/official

echo "Running extra tests..."
$DIR/test-cases $DIR/../ref/sxpy $1 $DIR/extra
